site_name: Data Analytics & AI Documentation
# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    # - content.tabs.link
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    # - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to automatic mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
# Plugins
plugins:
  - blog:
      blog_toc: true
  - tags
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocs-jupyter
  - swagger-ui-tag

hooks:
  - pyscripts/authors/authors.py
  - pyscripts/doculabels/doculabels.py

extra:
  authors:
    - Wilsven Leong:
        alias: wilsven
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/64478824?v=4
        url: https://github.com/Wilsven
    - Ong Tsien Jin:
        alias:
          - tsienjin
          - tjay
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/46650957?v=4
        url: https://github.com/TsienJin
    - Lyndon Lim:
        alias: lyndon
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/80683209?v=4
        url: https://github.com/lyndonlim27
    - Ho Si Xian:
        alias: Si Xian
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/60807138?v=4
        url: https://github.com/sixiannn
    - Joycelyn Woo:
        alias: joycelyn
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/139433726?v=4
        url: https://github.com/jwyting
    - Issac J:
        alias: issacj
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/68261814?v=4
        url: https://github.com/issacj-17
    - Jin Chou:
        alias: jinchou
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/74240198?v=4
        url: https://github.com/jinchad
    - Richmond Sin:
        alias: richmond
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/110978236?v=4
        url: https://github.com/richmondsin
    - Alexander Lee:
        alias: alex
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/97416749?v=4
        url: https://github.com/Varstak
    - Gowri Bhat:
        alias: gowri
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/97337263?v=4
        url: https://github.com/gowribhat

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - styles/mermaid.css
  - styles/author.css
  - styles/doculabels.css

nav:
  - Home:
      - index.md
      - Contribution Guides:
          - home/contribution_guides/introduction.md
          - home/contribution_guides/formatting.md
          - home/contribution_guides/endpoints.md
          - home/contribution_guides/classes_types_and_all.md
      - Hooks:
          - home/hooks/authors.md
          - home/hooks/doculabels.md
  - Projects:
      - Conversational Assistant:
          - Webapp:
              - Frontend:
                  - projects/genai/conversational-assistant/webapp/frontend/index.md
                  - Services:
                      - projects/genai/conversational-assistant/webapp/frontend/services/voice-activity-detection.md
                      - projects/genai/conversational-assistant/webapp/frontend/services/chat-message.md
                      - projects/genai/conversational-assistant/webapp/frontend/services/audio-player.md
                      - projects/genai/conversational-assistant/webapp/frontend/services/endpoint.md
                      - projects/genai/conversational-assistant/webapp/frontend/services/conversation-broker.md
                      - projects/genai/conversational-assistant/webapp/frontend/services/preference.md
                      - projects/genai/conversational-assistant/webapp/frontend/services/audio-service.md
                      - projects/genai/conversational-assistant/webapp/frontend/services/profile-service.md

              - Backend:
                  - API:
                      - projects/genai/conversational-assistant/webapp/backend/api/endpoints.md
  - Articles:
      - blog/index.md
